
# Provide your credentials
$cred = Get-Credential


# ServiceNow instance details
$ServiceNowInstance = "aklcdev"

# ServiceNow instance Personal
$ServiceNowInstance = "dev185867"

# ServiceNow instance 
$baseUrl = New-ServiceNowSession -Url "${ServiceNowInstance}.service-now.com" -Credential $cred


#Get Tasks from RITM
#$ritmDetails = Get-ServiceNowRecord -ParentId RITM0341949
$ritmDetails = Get-ServiceNowRecord -Id RITM0337385
$ritm_sys_id = $ritmDetails.sys_id

# ServiceNow REST API URL for the specified RITM
$Url = "https://${ServiceNowInstance}.service-now.com/api/now/table/sc_req_item/${ritm_sys_id}?sysparm_display_value=true&sysparm_fields=assigned_to%2Cassignment_group%2Cshort_description%2Cdescription%2Ccomments"
# Specify HTTP method
$method = "patch"

# JSON payload with the fields you want to modify
$body = "{
    `"assigned_to`":`"Elaine Ma`",
    `"assignment_group`":`"Service Site Panuku - Takapuna`",
    `"short_description`":`"This is Generated by PowerShekll2`",
    `"description`":`"This is Generated by PowerShekl2l`",
     `"comments`":`"This is Generated by PowerShekll for Description`"
    }"


# Make the HTTP request to update the task
$response = Invoke-RestMethod -Uri $Url -Method $method -Credential $cred -Headers @{ "Content-Type" = "application/json" } -Body $body


$response.result

