
# Provide your credentials
$cred = Get-Credential


# ServiceNow instance details
$ServiceNowInstance = "aklcdev"

# ServiceNow instance Personal
$ServiceNowInstance = "dev185867"

# ServiceNow instance 
$baseUrl = New-ServiceNowSession -Url "${ServiceNowInstance}.service-now.com" -Credential $cred

# Specify endpoint uri
$uri = "https://aklcdev.service-now.com/api/now/table/incident?sysparm_exclude_reference_link=true&sysparm_fields=number%2Cshort_description"

# Specify HTTP method
$method = "post"

# JSON payload with the fields you want to modify
$body = @{
    short_description = "Generated by PowerShell12345678987654321"
   
} | ConvertTo-Json

# Send HTTP request
$response = Invoke-RestMethod -Headers @{ "Content-Type" = "application/json" } -Method $method -Credential $cred -Uri $uri -Body $body

# Print response
$response.result
